### ISSUE TITLE
Request for Modified Code of Generative Models Cited in the Paper

### ISSUE THREAD

**Issue by JasonShao55** [liyucheng09/Metaphor_Generator#2]
Hi Yucheng, I hope this message finds you well. I was wondering if you could provide the specific modified code and instructions for the other generative models used in your paper, particularly for SeqGan. Since SeqGan was originally constructed using Python 2 and earlier versions of related libraries, it would be greatly appreciated if you could share the details of how you adapted it for metaphor generation tasks based on the original repository.

Additionally, if you still have the test_result.txt files for each model, would it be possible for you to share them with me? I am hoping to conduct similar experiments in my research.

I believe that if my work goes well, your paper will be frequently cited, which would benefit us both.

Thank you for your time and consideration. I look forward to hearing from you.

**Comment by liyucheng09** [comment]
Please find the my implementation of SeqGAN under our metaphor generation experiments at [here](https://drive.google.com/file/d/1LMMav5PGVZmGgyUroe6ZyCM67RSr9m1O/view?usp=drive_link). You can use the pre-trained parameters down in the `.save` folder directly to replicate the original results.

Let me know if you have further questions. if it has solved your issue, please close the issue.

**Comment by JasonShao55** [comment]
Sure I shall try it these days.

**Comment by JasonShao55** [comment]
Please accept my application to access the Google Drive's file.

**Comment by liyucheng09** [comment]
try it again. now it should be fine

**Comment by JasonShao55** [comment]
Now I'm able to download it.
Thanks.

liyucheng09 ***@***.***> 于2023年7月13日周四 22:28写道：

**Comment by JasonShao55** [comment]
Hi, due to change of plan we have decided not to apply SeqGan in our work. I suppose this issue should be closed.
